# Generated by Django 5.2.16 on 2026-07-09 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_key_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ordered', 'Ordered'), ('abandoned', 'Abandoned')], db_index=True, default='active', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_snapshot', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.cart')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='catalog.productlisting')),
                ('listing_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='catalog.productlistingvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=40, unique=True)),
                ('guest_order_key_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('payment_pending', 'Payment pending'), ('paid', 'Paid'), ('payment_failed', 'Payment failed')], db_index=True, default='payment_pending', max_length=30)),
                ('buyer_name', models.CharField(max_length=120)),
                ('buyer_phone', models.CharField(max_length=40)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_name', models.CharField(max_length=120)),
                ('recipient_phone', models.CharField(max_length=40)),
                ('postal_code', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=240)),
                ('address2', models.CharField(blank=True, max_length=240)),
                ('delivery_memo', models.CharField(blank=True, max_length=240)),
                ('items_subtotal', models.PositiveBigIntegerField(default=0)),
                ('shipping_fee', models.PositiveBigIntegerField(default=0)),
                ('coupon_discount_amount', models.PositiveBigIntegerField(default=0)),
                ('point_used_amount', models.PositiveBigIntegerField(default=0)),
                ('payment_amount', models.PositiveBigIntegerField(default=0)),
                ('sabangnet_status', models.CharField(db_index=True, default='not_sent', max_length=30)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_code_snapshot', models.CharField(max_length=80)),
                ('listing_name_snapshot', models.CharField(max_length=240)),
                ('listing_price_source_snapshot', models.CharField(max_length=40)),
                ('product_name_snapshot', models.CharField(max_length=240)),
                ('option_name_snapshot', models.CharField(blank=True, max_length=240)),
                ('sabangnet_product_code', models.CharField(max_length=80)),
                ('custom_product_code', models.CharField(blank=True, max_length=80)),
                ('barcode_snapshot', models.CharField(blank=True, max_length=120)),
                ('ordered_quantity', models.PositiveIntegerField()),
                ('cancelled_quantity', models.PositiveIntegerField(default=0)),
                ('returned_quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.PositiveBigIntegerField()),
                ('discount_amount', models.PositiveBigIntegerField(default=0)),
                ('line_total', models.PositiveBigIntegerField()),
                ('review_status', models.CharField(default='not_available', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productlisting')),
                ('listing_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productlistingvariant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='commerce.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='toss_payments', max_length=40)),
                ('customer_key_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('toss_order_id', models.CharField(db_index=True, max_length=80)),
                ('order_name', models.CharField(max_length=240)),
                ('expected_amount', models.PositiveBigIntegerField()),
                ('redirect_payment_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('redirect_amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('fail_code', models.CharField(blank=True, max_length=80)),
                ('safe_fail_message', models.CharField(blank=True, max_length=240)),
                ('confirm_idempotency_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('unknown', 'Unknown')], db_index=True, default='created', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('payload_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='commerce.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='toss_payments', max_length=40)),
                ('payment_key', models.CharField(max_length=200, unique=True)),
                ('toss_order_id', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(db_index=True, max_length=40)),
                ('method', models.CharField(blank=True, max_length=40)),
                ('total_amount', models.PositiveBigIntegerField()),
                ('balance_amount', models.PositiveBigIntegerField()),
                ('raw_response_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='commerce.order')),
                ('attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='commerce.paymentattempt')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), ('user__isnull', False)), fields=('user',), name='unique_active_cart_per_user'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_key_hash__isnull', False), ('status', 'active')), fields=('guest_key_hash',), name='unique_active_cart_per_guest'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'listing_variant'), name='unique_cart_listing_variant'),
        ),
    ]
