# Generated by Django 5.2.16 on 2026-07-12 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_order_fulfillment_status_order_sabangnet_order_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment pending'), ('paid', 'Paid'), ('payment_failed', 'Payment failed'), ('cancelled', 'Cancelled')], db_index=True, default='payment_pending', max_length=30),
        ),
        migrations.CreateModel(
            name='OrderCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='requested', max_length=20)),
                ('idempotency_key', models.CharField(max_length=80, unique=True)),
                ('cancel_amount', models.PositiveBigIntegerField()),
                ('transaction_key', models.CharField(blank=True, max_length=200)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('failure_message', models.CharField(blank=True, max_length=240)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation', to='commerce.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellations', to='commerce.payment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_cancellations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
