# Generated by Django 5.2.16 on 2026-07-12 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_alter_order_status_ordercancellation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabangnet_order_no', models.CharField(blank=True, db_index=True, max_length=80)),
                ('carrier_code', models.CharField(blank=True, max_length=80)),
                ('carrier_name', models.CharField(blank=True, max_length=120)),
                ('tracking_number', models.CharField(db_index=True, max_length=160)),
                ('status', models.CharField(blank=True, db_index=True, max_length=30)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('raw_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='commerce.order')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('order', 'carrier_code', 'tracking_number'), name='unique_order_carrier_tracking_number')],
            },
        ),
    ]
