# Generated by Django 5.2.16 on 2026-07-12 05:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_shipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('partial_cancel', 'Partial cancellation'), ('exchange', 'Exchange'), ('return', 'Return')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='requested', max_length=20)),
                ('reason', models.CharField(max_length=240)),
                ('detail', models.TextField(blank=True)),
                ('refund_amount', models.PositiveBigIntegerField(default=0)),
                ('restored_point_amount', models.PositiveBigIntegerField(default=0)),
                ('idempotency_key', models.CharField(default=uuid.uuid4, max_length=80, unique=True)),
                ('transaction_key', models.CharField(blank=True, max_length=200)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('failure_message', models.CharField(blank=True, max_length=240)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='commerce.order')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderClaimItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.orderclaim')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_items', to='commerce.orderitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('claim', 'order_item'), name='unique_claim_order_item')],
            },
        ),
    ]
