# Generated by Django 5.2.16 on 2026-07-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_orderclaim_orderclaimitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_reservation_status',
            field=models.CharField(choices=[('none', 'Not reserved'), ('reserved', 'Reserved locally'), ('consumed', 'Reflected in source stock'), ('released', 'Released')], db_index=True, default='none', max_length=20),
        ),
    ]
