# Generated by Django 5.2.16 on 2026-07-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_order_inventory_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderclaim',
            name='claim_type',
            field=models.CharField(choices=[('exchange', 'Exchange'), ('return', 'Return')], db_index=True, max_length=30),
        ),
    ]
