# Generated by Django 5.2.16 on 2026-07-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_productreviewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviewimage',
            name='image',
            field=models.ImageField(upload_to='reviews/%Y/%m/'),
        ),
    ]
