# Generated by Django 5.2.16 on 2026-07-12 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=40, unique=True)),
                ('identity_verified_at', models.DateTimeField(blank=True, null=True)),
                ('terms_agreed_at', models.DateTimeField()),
                ('marketing_agreed', models.BooleanField(default=False)),
                ('marketing_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('kakao', 'Kakao'), ('naver', 'Naver')], max_length=20)),
                ('provider_user_id', models.CharField(max_length=200)),
                ('provider_email', models.EmailField(blank=True, max_length=254)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='unique_social_provider_per_user'), models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='unique_social_provider_identity')],
            },
        ),
    ]
