"""Korean labels used by the internal Django administration interface.

These labels are presentation metadata only, so applying them at startup avoids
schema-only migrations while keeping the database and external API contracts
unchanged.
"""

from django.apps import apps


MODEL_LABELS = {
    "catalog.Brand": ("브랜드", "브랜드"),
    "catalog.Category": ("카테고리", "카테고리"),
    "catalog.Product": ("상품", "상품"),
    "catalog.ProductVariant": ("상품 옵션", "상품 옵션"),
    "catalog.ProductImage": ("상품 이미지", "상품 이미지"),
    "catalog.ProductInformationNotice": ("상품정보 제공고시", "상품정보 제공고시"),
    "catalog.ProductAttribute": ("상품 속성", "상품 속성"),
    "catalog.SearchKeyword": ("검색어", "검색어"),
    "catalog.ProductSyncSnapshot": ("상품 동기화 기록", "상품 동기화 기록"),
    "catalog.ProductListing": ("판매 상품", "판매 상품"),
    "catalog.ProductListingVariant": ("판매 상품 옵션", "판매 상품 옵션"),
    "commerce.Cart": ("장바구니", "장바구니"),
    "commerce.CartItem": ("장바구니 상품", "장바구니 상품"),
    "commerce.Order": ("주문", "주문"),
    "commerce.OrderItem": ("주문 상품", "주문 상품"),
    "commerce.PaymentAttempt": ("결제 시도", "결제 시도"),
    "commerce.Payment": ("결제 내역", "결제 내역"),
    "commerce.OrderStatusHistory": ("주문 상태 변경 기록", "주문 상태 변경 기록"),
    "commerce.Shipment": ("배송 정보", "배송 정보"),
    "commerce.OrderCancellation": ("주문 취소", "주문 취소"),
    "commerce.OrderClaim": ("교환·반품 요청", "교환·반품 요청"),
    "commerce.OrderClaimItem": ("교환·반품 상품", "교환·반품 상품"),
    "integrations.SabangnetOrderExport": ("사방넷 주문 전송", "사방넷 주문 전송"),
    "integrations.IntegrationJob": ("연동 작업", "연동 작업"),
    "integrations.ExternalApiLog": ("외부 API 로그", "외부 API 로그"),
    "integrations.OperationsAuditLog": ("관리자 작업 기록", "관리자 작업 기록"),
    "accounts.MemberProfile": ("회원 프로필", "회원 프로필"),
    "accounts.SocialConnection": ("소셜 계정 연결", "소셜 계정 연결"),
    "accounts.WishlistItem": ("찜한 상품", "찜한 상품"),
    "accounts.RecentlyViewedItem": ("최근 본 상품", "최근 본 상품"),
    "accounts.ShippingAddress": ("배송지", "배송지"),
    "content.HomeBanner": ("홈 배너", "홈 배너"),
    "content.EditorialCollection": ("기획 컬렉션", "기획 컬렉션"),
    "content.CollectionListing": ("컬렉션 상품", "컬렉션 상품"),
    "content.Promotion": ("프로모션", "프로모션"),
    "content.PromotionListing": ("프로모션 상품", "프로모션 상품"),
    "content.Lookbook": ("룩북", "룩북"),
    "content.LookbookImage": ("룩북 이미지", "룩북 이미지"),
    "content.LookbookListing": ("룩북 상품", "룩북 상품"),
    "content.Notice": ("공지사항", "공지사항"),
    "content.FAQ": ("자주 묻는 질문", "자주 묻는 질문"),
    "content.PolicyPage": ("정책 페이지", "정책 페이지"),
    "community.ProductReview": ("상품 리뷰", "상품 리뷰"),
    "community.ProductReviewImage": ("리뷰 이미지", "리뷰 이미지"),
    "community.CustomerInquiry": ("고객 문의", "고객 문의"),
    "benefits.ShippingPolicy": ("배송 정책", "배송 정책"),
    "benefits.MemberTier": ("회원 등급", "회원 등급"),
    "benefits.MemberBenefitAccount": ("회원 혜택 계정", "회원 혜택 계정"),
    "benefits.Coupon": ("쿠폰", "쿠폰"),
    "benefits.MemberCoupon": ("회원 보유 쿠폰", "회원 보유 쿠폰"),
    "benefits.CouponUsage": ("쿠폰 사용 내역", "쿠폰 사용 내역"),
    "benefits.PointLedger": ("포인트 내역", "포인트 내역"),
}


FIELD_LABELS = {
    "id": "ID", "name": "이름", "code": "코드", "status": "상태", "user": "회원",
    "created_at": "등록일시", "updated_at": "수정일시", "starts_at": "시작일시", "ends_at": "종료일시",
    "parent": "상위 카테고리", "slug": "URL 식별자", "logo_image": "로고 이미지 URL",
    "hero_image": "대표 이미지 URL", "hero_image_url": "대표 이미지 URL", "description": "설명",
    "sort_order": "노출 순서", "is_visible": "노출 여부", "brand": "브랜드", "category": "카테고리",
    "product": "상품", "listing": "판매 상품", "variant": "상품 옵션", "listing_variant": "판매 상품 옵션",
    "sabangnet_code": "사방넷 카테고리 코드", "sabangnet_product_code": "사방넷 상품코드",
    "custom_product_code": "자체상품코드", "english_name": "영문 상품명", "model_name": "모델명",
    "manufacturer_name": "제조사", "origin_name": "원산지", "consumer_price": "소비자가",
    "selling_price": "판매가", "cost_price": "원가", "tax_code": "과세 구분", "supply_status": "공급 상태",
    "target_code": "대상 코드", "season_code": "시즌 코드", "product_tags": "상품 태그",
    "detail_html": "상품 상세 HTML", "synced_at": "최근 동기화", "raw_sabangnet_payload": "사방넷 원본 데이터",
    "variant_code": "옵션 코드", "sabangnet_option_id": "사방넷 옵션 ID", "barcode": "바코드",
    "option_display_name": "옵션 표시명", "additional_amount": "추가 금액", "stock_quantity": "재고 수량",
    "reserved_quantity": "예약 재고", "safety_stock_quantity": "안전 재고", "source": "등록 출처",
    "sabangnet_image_srno": "사방넷 이미지 번호", "image_url": "이미지 URL", "image_urls": "이미지 URL 목록",
    "alt_text": "대체 문구", "is_primary": "대표 이미지", "notice_type": "고시 유형", "fields": "고시 항목",
    "value": "값", "is_filterable": "검색 필터 사용", "keyword": "검색어", "search_count": "검색 횟수",
    "is_recommended": "추천 검색어", "last_searched_at": "최근 검색일시", "field_changes": "변경 내용",
    "error_message": "오류 메시지", "listing_code": "판매 상품 코드", "sales_channel": "판매 채널",
    "display_name": "표시 상품명", "listing_summary": "상품 요약", "listing_detail_html": "판매 상세 HTML",
    "seo_title": "검색 제목", "seo_description": "검색 설명", "is_featured": "대표 상품",
    "is_new_label": "신상품 표시", "is_sale_label": "할인 표시", "consumer_price_snapshot": "소비자가 기준값",
    "selling_price_snapshot": "판매가 기준값", "discount_rate_snapshot": "할인율 기준값", "price_source": "가격 출처",
    "search_keywords": "검색 키워드", "additional_amount_snapshot": "추가 금액 기준값",
    "stock_display_policy": "재고 표시 정책", "guest_key_hash": "비회원 키", "expires_at": "만료일시",
    "cart": "장바구니", "quantity": "수량", "unit_price_snapshot": "단가 기준값", "order": "주문",
    "order_number": "주문번호", "guest_order_key_hash": "비회원 주문 키", "buyer_name": "주문자명",
    "buyer_phone": "주문자 연락처", "buyer_email": "주문자 이메일", "recipient_name": "수령인명",
    "recipient_phone": "수령인 연락처", "postal_code": "우편번호", "address1": "기본 주소",
    "address2": "상세 주소", "delivery_memo": "배송 메모", "items_subtotal": "상품 금액",
    "shipping_fee": "배송비", "coupon_discount_amount": "쿠폰 할인액", "point_used_amount": "포인트 사용액",
    "payment_amount": "최종 결제액", "sabangnet_status": "사방넷 전송 상태", "sabangnet_order_no": "사방넷 주문번호",
    "sabangnet_order_status": "사방넷 주문 상태", "sabangnet_status_synced_at": "사방넷 상태 동기화일시",
    "fulfillment_status": "배송 처리 상태", "inventory_reservation_status": "재고 예약 상태", "paid_at": "결제일시",
    "ordered_at": "주문일시", "order_item": "주문 상품", "listing_code_snapshot": "판매 상품 코드 기준값",
    "listing_name_snapshot": "판매 상품명 기준값", "listing_price_source_snapshot": "가격 출처 기준값",
    "product_name_snapshot": "상품명 기준값", "option_name_snapshot": "옵션명 기준값", "barcode_snapshot": "바코드 기준값",
    "ordered_quantity": "주문 수량", "cancelled_quantity": "취소 수량", "returned_quantity": "반품 수량",
    "unit_price": "단가", "discount_amount": "할인 금액", "line_total": "합계 금액", "review_status": "리뷰 상태",
    "provider": "연동 서비스", "customer_key_hash": "고객 키", "toss_order_id": "토스 주문 ID",
    "order_name": "주문명", "expected_amount": "예상 결제액", "redirect_payment_key": "리다이렉트 결제 키",
    "redirect_amount": "리다이렉트 결제액", "fail_code": "실패 코드", "safe_fail_message": "고객 안내 실패 문구",
    "confirm_idempotency_key": "승인 중복방지 키", "payload_summary": "요청 데이터 요약", "attempt": "결제 시도",
    "payment_key": "결제 키", "method": "결제 수단", "total_amount": "총 결제액", "balance_amount": "취소 가능 잔액",
    "raw_response_summary": "원본 응답 요약", "previous_status": "이전 상태", "new_status": "변경 상태",
    "raw_external_status": "외부 원본 상태", "note": "메모", "carrier_code": "택배사 코드", "carrier_name": "택배사명",
    "tracking_number": "운송장 번호", "shipped_at": "출고일시", "delivered_at": "배송 완료일시", "raw_summary": "원본 요약",
    "payment": "결제 내역", "requested_by": "요청자", "reason": "사유", "idempotency_key": "중복방지 키",
    "cancel_amount": "취소 금액", "transaction_key": "거래 키", "failure_code": "실패 코드",
    "failure_message": "실패 메시지", "requested_at": "요청일시", "completed_at": "완료일시",
    "claim_type": "요청 유형", "detail": "상세 사유", "refund_amount": "환불 금액",
    "restored_point_amount": "복원 포인트", "claim": "교환·반품 요청", "generated_at": "생성일시",
    "filename": "파일명", "row_count": "행 수", "job_type": "작업 유형", "started_at": "시작일시",
    "finished_at": "종료일시", "total_count": "전체 건수", "success_count": "성공 건수",
    "failure_count": "실패 건수", "error_summary": "오류 요약", "job": "연동 작업", "operation": "작업명",
    "request_summary": "요청 요약", "response_status": "응답 상태 코드", "response_summary": "응답 요약",
    "error_code": "오류 코드", "duration_ms": "처리 시간(ms)", "actor": "작업자", "action": "작업 내용",
    "target_type": "대상 유형", "target_id": "대상 ID", "before_summary": "변경 전", "after_summary": "변경 후",
    "ip_address": "IP 주소", "phone": "연락처", "identity_verified_at": "본인인증일시",
    "terms_agreed_at": "약관 동의일시", "marketing_agreed": "마케팅 수신 동의", "marketing_agreed_at": "마케팅 동의일시",
    "provider_user_id": "외부 회원 ID", "provider_email": "외부 계정 이메일", "connected_at": "연결일시",
    "last_login_at": "최근 로그인", "viewed_at": "조회일시", "label": "배송지 이름", "is_default": "기본값",
    "title": "제목", "subtitle": "부제목", "media_type": "미디어 유형", "media_url": "미디어 URL",
    "mobile_media_url": "모바일 미디어 URL", "poster_url": "포스터 URL", "link_type": "링크 유형",
    "link_url": "링크 URL", "button_label": "버튼 문구", "summary": "요약", "collection": "컬렉션",
    "promotion": "프로모션", "body_html": "본문 HTML", "lookbook": "룩북", "season_label": "시즌명",
    "cover_image_url": "표지 이미지 URL", "caption": "이미지 설명", "content": "내용", "is_pinned": "상단 고정",
    "published_at": "게시일시", "question": "질문", "answer": "답변", "policy_type": "정책 유형",
    "version": "버전", "effective_at": "시행일", "rating": "평점", "body": "내용", "review": "리뷰",
    "image": "이미지", "subject": "문의 제목", "answered_at": "답변일시", "base_fee": "기본 배송비",
    "free_shipping_threshold": "무료배송 기준", "is_active": "사용 여부", "minimum_purchase_amount": "최소 구매금액",
    "minimum_order_count": "최소 주문횟수", "discount_rate": "할인율", "point_earn_rate": "포인트 적립률",
    "tier": "회원 등급", "point_balance": "포인트 잔액", "lifetime_purchase_amount": "누적 구매금액",
    "completed_order_count": "완료 주문수", "tier_expires_at": "등급 만료일", "discount_type": "할인 유형",
    "discount_value": "할인 값", "minimum_order_amount": "최소 주문금액", "maximum_discount_amount": "최대 할인금액",
    "coupon": "쿠폰", "issued_at": "발급일시", "used_at": "사용일시", "member_coupon": "회원 보유 쿠폰",
    "restored_at": "복원일시", "account": "혜택 계정", "amount": "금액", "balance_after": "처리 후 잔액",
}


def apply_admin_localization():
    for model in apps.get_models():
        label = model._meta.label
        if label in MODEL_LABELS:
            model._meta.verbose_name, model._meta.verbose_name_plural = MODEL_LABELS[label]
        for field in model._meta.fields:
            if field.name in FIELD_LABELS:
                field.verbose_name = FIELD_LABELS[field.name]
