# Generated by Django 5.2.16 on 2026-07-12 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0004_shipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed amount'), ('percent', 'Percentage'), ('free_shipping', 'Free shipping')], max_length=20)),
                ('discount_value', models.PositiveBigIntegerField(default=0)),
                ('minimum_order_amount', models.PositiveBigIntegerField(default=0)),
                ('maximum_discount_amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('minimum_purchase_amount', models.PositiveBigIntegerField(default=0)),
                ('minimum_order_count', models.PositiveIntegerField(default=0)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('point_earn_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'minimum_purchase_amount'],
            },
        ),
        migrations.CreateModel(
            name='MemberCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('used', 'Used'), ('expired', 'Expired')], db_index=True, default='available', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_coupons', to='benefits.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_coupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.PositiveBigIntegerField()),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_usage', to='commerce.order')),
                ('member_coupon', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='usage', to='benefits.membercoupon')),
            ],
        ),
        migrations.CreateModel(
            name='MemberBenefitAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_balance', models.BigIntegerField(default=0)),
                ('lifetime_purchase_amount', models.PositiveBigIntegerField(default=0)),
                ('completed_order_count', models.PositiveIntegerField(default=0)),
                ('tier_expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_account', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='benefits.membertier')),
            ],
        ),
        migrations.CreateModel(
            name='PointLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('balance_after', models.BigIntegerField()),
                ('reason', models.CharField(choices=[('order_use', 'Order use'), ('order_earn', 'Order earn'), ('review_earn', 'Review earn'), ('cancel_restore', 'Cancellation restore'), ('admin', 'Admin adjustment'), ('expire', 'Expiration')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='point_ledger', to='benefits.memberbenefitaccount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='point_ledger', to='commerce.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('base_fee', models.PositiveBigIntegerField(default=0)),
                ('free_shipping_threshold', models.PositiveBigIntegerField(default=0)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_shipping_policy')],
            },
        ),
        migrations.AddConstraint(
            model_name='membercoupon',
            constraint=models.UniqueConstraint(fields=('user', 'coupon'), name='unique_member_coupon'),
        ),
    ]
