# Generated by Django 5.2.16 on 2026-07-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointledger',
            name='reason',
            field=models.CharField(choices=[('order_use', 'Order use'), ('order_earn', 'Order earn'), ('order_earn_reversal', 'Order earn reversal'), ('review_earn', 'Review earn'), ('cancel_restore', 'Cancellation restore'), ('admin', 'Admin adjustment'), ('expire', 'Expiration')], max_length=30),
        ),
    ]
