# Generated by Django 5.2.16 on 2026-07-09 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SabangnetOrderSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying')], db_index=True, default='pending', max_length=20)),
                ('sabangnet_order_no', models.CharField(blank=True, db_index=True, max_length=80)),
                ('operation_idempotency_key', models.CharField(db_index=True, max_length=160)),
                ('external_request_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('terminal_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('payload_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sabangnet_submission', to='commerce.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'operation_idempotency_key'), name='unique_sabangnet_submission_idempotency')],
            },
        ),
    ]
