# Generated by Django 5.2.16 on 2026-07-12 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_integrationjob_externalapilog_operationsauditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationjob',
            options={'ordering': ['-created_at'], 'permissions': [('view_operations_dashboard', 'Can view operations dashboard'), ('reconcile_payment', 'Can reconcile payment'), ('retry_integration', 'Can retry integration jobs'), ('manage_shipping_policy', 'Can manage shipping policy'), ('view_sensitive_pii', 'Can view unmasked customer PII')]},
        ),
    ]
