# Generated by Django 5.2.16 on 2026-07-09 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('logo_image', models.URLField(blank=True)),
                ('hero_image', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('sabangnet_code', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
            ],
            options={
                'ordering': ['level', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabangnet_product_code', models.CharField(max_length=80, unique=True)),
                ('custom_product_code', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('english_name', models.CharField(blank=True, max_length=240)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('manufacturer_name', models.CharField(blank=True, max_length=120)),
                ('origin_name', models.CharField(blank=True, max_length=120)),
                ('consumer_price', models.PositiveBigIntegerField(default=0)),
                ('selling_price', models.PositiveBigIntegerField(default=0)),
                ('cost_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tax_code', models.CharField(max_length=40)),
                ('supply_status', models.CharField(db_index=True, max_length=40)),
                ('target_code', models.CharField(blank=True, max_length=40)),
                ('season_code', models.CharField(blank=True, max_length=40)),
                ('product_tags', models.CharField(blank=True, max_length=500)),
                ('detail_html', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('raw_sabangnet_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_code', models.CharField(max_length=80, unique=True)),
                ('sales_channel', models.CharField(default='main_mall', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('display_name', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=260)),
                ('listing_summary', models.TextField(blank=True)),
                ('listing_detail_html', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=240)),
                ('seo_description', models.CharField(blank=True, max_length=500)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new_label', models.BooleanField(default=False)),
                ('is_sale_label', models.BooleanField(default=False)),
                ('consumer_price_snapshot', models.PositiveBigIntegerField(default=0)),
                ('selling_price_snapshot', models.PositiveBigIntegerField(default=0)),
                ('discount_rate_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_source', models.CharField(default='sabangnet', max_length=40)),
                ('search_keywords', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_code', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('sabangnet_option_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=120)),
                ('option_display_name', models.CharField(max_length=240)),
                ('additional_amount', models.BigIntegerField(default=0)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('safety_stock_quantity', models.IntegerField(default=0)),
                ('supply_status', models.CharField(db_index=True, max_length=40)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductListingVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden'), ('sold_out', 'Sold out'), ('paused', 'Paused')], db_index=True, default='active', max_length=20)),
                ('additional_amount_snapshot', models.BigIntegerField(default=0)),
                ('stock_display_policy', models.CharField(default='show', max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.productlisting')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_variants', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('slug',), name='unique_root_category_slug'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'slug'), name='unique_child_category_slug'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'category', 'supply_status'], name='catalog_pro_brand_i_70af14_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['selling_price'], name='catalog_pro_selling_a333a1_idx'),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['sales_channel', 'status', 'starts_at', 'ends_at'], name='catalog_pro_sales_c_672784_idx'),
        ),
        migrations.AddConstraint(
            model_name='productlisting',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('product', 'sales_channel'), name='unique_active_listing_per_product_channel'),
        ),
        migrations.AddConstraint(
            model_name='productlisting',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'scheduled'])), fields=('slug',), name='unique_public_listing_slug'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'option_display_name'), name='unique_variant_display_name_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('barcode',), name='unique_nonblank_variant_barcode'),
        ),
        migrations.AddConstraint(
            model_name='productlistingvariant',
            constraint=models.UniqueConstraint(fields=('listing', 'variant'), name='unique_variant_per_listing'),
        ),
    ]
