# Generated by Django 5.2.16 on 2026-07-12 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSyncSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabangnet_product_code', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('failed', 'Failed')], db_index=True, max_length=20)),
                ('field_changes', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_snapshots', to='catalog.product')),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('sabangnet', 'Sabangnet'), ('admin', 'Admin')], default='sabangnet', max_length=20)),
                ('sabangnet_image_srno', models.CharField(blank=True, max_length=80)),
                ('image_url', models.URLField(max_length=1000)),
                ('alt_text', models.CharField(blank=True, max_length=240)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('sabangnet_image_srno', ''), _negated=True), fields=('product', 'source', 'sabangnet_image_srno'), name='unique_product_source_image_srno'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_image_per_product')],
            },
        ),
    ]
