# Generated by Django 5.2.16 on 2026-07-12 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productsyncsnapshot_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=120, unique=True)),
                ('search_count', models.PositiveBigIntegerField(default=0)),
                ('is_recommended', models.BooleanField(db_index=True, default=False)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('last_searched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sort_order', '-search_count', 'keyword'],
            },
        ),
        migrations.CreateModel(
            name='ProductInformationNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(blank=True, max_length=120)),
                ('fields', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='sabangnet', max_length=20)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='information_notice', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('value', models.CharField(db_index=True, max_length=160)),
                ('is_filterable', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(default='sabangnet', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', 'name', 'value'],
                'constraints': [models.UniqueConstraint(fields=('product', 'name', 'value'), name='unique_product_attribute_value')],
            },
        ),
    ]
