# Generated by Django 5.2.16 on 2026-07-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_searchkeyword_productinformationnotice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
