# Generated by Django 5.2.16 on 2026-07-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_korean_choice_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlistingvariant',
            name='status',
            field=models.CharField(choices=[('draft', '작성 중'), ('active', '판매 중'), ('hidden', '숨김'), ('sold_out', '품절'), ('paused', '판매 일시중지')], db_index=True, default='active', max_length=20),
        ),
    ]
