# Generated by Django 5.2.16 on 2026-07-12 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('media_url', models.URLField()),
                ('mobile_media_url', models.URLField(blank=True)),
                ('poster_url', models.URLField(blank=True)),
                ('link_type', models.CharField(choices=[('none', 'None'), ('listing', 'Product listing'), ('brand', 'Brand'), ('collection', 'Collection'), ('external', 'External URL')], default='none', max_length=20)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('button_label', models.CharField(blank=True, max_length=80)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_links', to='catalog.productlisting')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EditorialCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('hero_image_url', models.URLField(blank=True)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listings', models.ManyToManyField(related_name='collections', through='content.CollectionListing', to='catalog.productlisting')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='collectionlisting',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_listings', to='content.editorialcollection'),
        ),
        migrations.AddConstraint(
            model_name='collectionlisting',
            constraint=models.UniqueConstraint(fields=('collection', 'listing'), name='unique_collection_listing'),
        ),
    ]
