# Generated by Django 5.2.16 on 2026-07-12 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_searchkeyword_productinformationnotice_and_more'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=80)),
                ('question', models.CharField(max_length=240)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('terms', 'Terms'), ('privacy', 'Privacy'), ('shipping', 'Shipping'), ('returns', 'Returns')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('version', models.CharField(max_length=40)),
                ('is_visible', models.BooleanField(default=True)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('hero_image_url', models.URLField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('season_label', models.CharField(blank=True, max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lookbooks', to='catalog.brand')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LookbookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('lookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.lookbook')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LookbookListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productlisting')),
                ('lookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookbook_listings', to='content.lookbook')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='lookbook',
            name='listings',
            field=models.ManyToManyField(related_name='lookbooks', through='content.LookbookListing', to='catalog.productlisting'),
        ),
        migrations.CreateModel(
            name='PromotionListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productlisting')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_listings', to='content.promotion')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='promotion',
            name='listings',
            field=models.ManyToManyField(related_name='promotions', through='content.PromotionListing', to='catalog.productlisting'),
        ),
        migrations.AddConstraint(
            model_name='lookbooklisting',
            constraint=models.UniqueConstraint(fields=('lookbook', 'listing'), name='unique_lookbook_listing'),
        ),
        migrations.AddConstraint(
            model_name='promotionlisting',
            constraint=models.UniqueConstraint(fields=('promotion', 'listing'), name='unique_promotion_listing'),
        ),
    ]
